// seasonal veggie chart

window.VEGGIES = {
	Artichokes: [[3, 4, 5, 6, 9, 10, 11, 12],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/artichokes.jpg?itok=Fjs5Yql3"],
	Arugula: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/arugula_23.jpg?itok=Mlims1Dg"],
	Asparagus: [[2, 3, 4, 5, 6],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/asparagus_green_purple.JPG?itok=YwfdVFvu"],
	Beets: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/gold_beets.jpg?itok=PCu7q7Bk"],
	Bok_choy: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Bok_Choy.JPG?itok=Ur1dYLoJ"],
	Broccoli: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/broccoli.JPG?itok=XdfsaQRK"],
	Broccoli_rabe: [[1, 2, 3, 4, 5, 6, 9, 10, 11, 12],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/rapini.jpg?itok=bK-4la2U"],
	Brussels_sprouts: [[1, 2, 3, 4, 5, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/brussels_sprouts.JPG?itok=CdimINcj"],
	Burdock: [[7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/burdock_14.jpg?itok=ouGWxWcj"],
	Cabbage: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/cabbage.JPG?itok=x3i7br71"],
	Cactus_pads: [[5, 6, 7, 8, 9, 10], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Cactus_pads.JPG?itok=KY8d7leC"],
	Cardoons: [[1, 2, 3, 4, 5, 6, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/cardoons.jpg?itok=oljs1ODL"],
	Carrots: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/carrots_colorful.jpg?itok=pSya9Fa-"],
	Cauliflower: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/cauliflower.JPG?itok=ZVBweEwl"],
	Celeriac: [[4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Celeriac.JPG?itok=uDnm5pQL"],
	Celery: [[4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/celery2_5.jpg?itok=mPB7CLx8"],
	Chard: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/chard_6.jpg?itok=ZYngD70T"],
	Chicory: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/treviso_radicchio_0.jpg?itok=K7ixQrNm"],
	Collard_greens: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/collards_0.jpg?itok=buC9miBO"],	
	Corn: [[1, 2, 3, 4, 5, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/corn_6.jpg?itok=-Td3pHbc"],
	Cress: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/cress_15.jpg?itok=zD305sJR"],
	Cucumbers: [[6, 7, 8, 9, 10, 11], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/cucumbers_pickling_0.jpg?itok=bcvYf3Pe"],
	Dandelion_greens: [[1, 2, 3, 4, 5],	
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/dandelion_greens_7.jpg?itok=JHd6jM8W"],
	Eggplant: [[6, 7, 8, 9, 10], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/eggplant.JPG?itok=fkoxpNWp"],
	Endive: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/frisee_lonely_mountain.jpg?itok=gYS6oBUL"],
	Fava_beans: [[3, 4, 5, 6, 7], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/favas_cropped.jpg?itok=ujXBe5mZ"],
	Fava_greens: [[1, 2, 3, 4, 5], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/fava_greens_14.jpg?itok=wNJA91a_"],
	Fennel: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/fennel.JPG?itok=pFa3c0W5"],
	Garlic: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Garlic.jpg?itok=OXXpb-hs"],
	Green_beans: [[6, 7, 8, 9], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Green_beans.JPG?itok=l5y38BSs"],
	Green_garlic: [[2, 3, 4, 5, 6],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Green_garlic.jpg?itok=-f4I3s0r"],
	Herbs: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/herbs_display.jpg?itok=-Lxu5KEl"],
	Horseradish: [[2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/horseradish.JPG?itok=KifHGTV8"],
	Kale: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Kale.JPG?itok=HQt4BUoq"],
	Kohlrabi: [[1, 2, 3, 4, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Kohlrabi.JPG?itok=9NbHyvyW"],
	Lambsquarters: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/lambsquarters.JPG?itok=3tkwdhlt"],
	Leeks: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/leeks_pile_15.jpg?itok=VnBzGkQq"],
	Lettuce: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/lettuce.jpg?itok=na_swzDb"],
	Mizuna: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Mizuna.JPG?itok=2H0QIxVp"],
	Mushrooms: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Mushrooms.JPG?itok=hoePTRyC"],
	Mustard_greens: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Mustard_greens.JPG?itok=INl5cFlX"],
	Nettles: [[1, 2, 3, 4, 5, 6, 7],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/nettles_23.jpg?itok=ZSgYQCWd"],
	Okra: [[6, 7, 8, 9, 10, 11], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/okra_lucero.JPG?itok=lhayJFL0"],
	Onions: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Red_onions.jpg?itok=xpLGoskh"],
	Orach: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/RedOrach_14.jpg?itok=lcTJlX9N"],
	Parsnips: [[1, 2, 3, 4, 5, 10, 11, 12],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/parsnips.jpg?itok=VesT735N"],
	Pea_shoots: [[1, 2, 3, 4, 5],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/pea_shoots.jpg?itok=QsBlSfn8"],
	Peas: [[4, 5, 6, 7, 8, 9, 10, 11], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/peas_english_iacopi_16.jpg?itok=D8EXX_uQ"],
	Chile_peppers: [[7, 8, 9, 10, 11, 12],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/chiles_hot_tierra.JPG?itok=xYa2kL0N"],
	Sweet_Peppers: [[5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/assorted_peppers.JPG?itok=ShQ1T3-p"],
	Potatoes: [[6, 7, 8],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/potatoes_thomas.JPG?itok=WXRYR9S8"],
	Purslane: [[4, 5, 6, 7, 8, 9, 10, 11],
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/purslane_0.JPG?itok=pAXwSNib"],
	Radishes: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/radishes_multicolor.JPG?itok=e6m890Gh"],
	Rutabagas: [[1, 2, 3, 4, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Rutabagas.jpg?itok=8jQMKwqW"],
	Salsify: [[9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Salsify.JPG?itok=-BjWPE--"],
	Scallions: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/scallions_0.jpg?itok=IXFhZw7Q"],
	Shallots: [[5, 6, 7], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/shallots_14.jpg?itok=4hwbZM0V"],
	Shelling_beans: [[8, 9, 10], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Shelling_Beans.JPG?itok=lxq2ev0M"],
	Spinach: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/spinach_bordeaux_22.jpg?itok=D3JezlYs"],
	Sprouts: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/sprouts_sunflower_14.jpg?itok=twlX-JRF"],
	Summer_squash: [[6, 7, 8, 9, 10], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/squash_sunburst_14.jpg?itok=4ayBXDix"],
	Winter_squash: [[10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/hard_squash_lonely_mountain.JPG?itok=SJ-Rq5s3"],
	Sunchokes: [[1, 2, 3, 4, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/sunchokes.JPG?itok=hYTw8Rg5"],
	Sweet_potatoes: [[9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Sweet_Potatoes.JPG?itok=zfHq8fIi"],
	Tatsoi: [[1, 2, 3, 4, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/tatsoi.png?itok=khZpJCQF"],
	Tomatillos: [[6, 7, 8, 9, 10, 11], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/Tomatillos.JPG?itok=Z11sOntc"],
	Tomatoes: [[6, 7, 8, 9, 10], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/tomatoes_heirloom_lonely_mountain.JPG?itok=YR28CCRF"],
	Turnips: [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 
		"http://www.cuesa.org/sites/default/files/styles/article_feature_image_600/public/turnips_tokyo.JPG?itok=RBgdvSXq"],
	Yacon: [[11, 12], 
		"http://www.foodpyramid.com/wp-content/uploads/2014/09/yacon-root.jpg"]

}



// seasonal veggies chart
// http://www.cuesa.org/eat-seasonally/charts/vegetables